#!/bin/sh

# A dwm_bar function to print the rate of CURRENCY/USD from rate.sx using rate.sx/1CURRENCY
# Creator of the project: Joe Standring <git@joestandring.com>
# Additional plugin added by Brayan de Albuquerque <brayandealbuquerque@gmail.com>
# GNU GPLv3

# Dependencies: curl

# Change the value of CURRENCY to match your currency code
ENABLED=1
TARGET=5.2744

CURRENCY1=USD
CURRENCY2=BRL

dwm_currency() {
	if [ "$ENABLED" = 1 ]; then


		RATE=$(curl -s "https://api.frankfurter.app/latest?from=$CURRENCY1&to=$CURRENCY2" | jq -r ".rates.$CURRENCY2")
		printf " %s" "$(awk "BEGIN {printf \"%.2f (%.2f%%)\", $RATE, (1 - $RATE / $TARGET) * 100}")"
	else
		exit
	fi
}


work_hours() {
	day_of_week=$(date +%A)
	hour=$(date +%H)

	for x in Monday Tuesday Wednesday Thursday Friday; do
		if [ "$x" = "$day_of_week" ]; then
			if [ "$hour" -ge 8 ] && [ "$hour" -lt 17 ]; then
				dwm_currency
			fi
		fi
	done
}

work_hours
