#!/bin/sh

# A dwm_status function that displays the status of countdown.sh
# Joe Standring <git@joestandring.com>
# GNU GPLv3

# Dependencies: https://github.com/joestandring/countdown

# Exit early if no countdown is active
set -- /tmp/countdown.*
[ -e "$1" ] || exit 0

f="$1"

case "$BLOCK_BUTTON" in
    1)
        killall countdown
        rm -f "$f"
        notify-send "Countdown" "Cancelled"
        exit 0
        ;;
esac

read -r last < "$f" || exit 0

if [ "$IDENTIFIER" = "unicode" ]; then
    printf "%s⏳ %s%s\n" "$SEP1" "$last" "$SEP2"
else
    printf "%sCDN %s%s\n" "$SEP1" "$last" "$SEP2"
fi
