#!/bin/sh

# A dwm_bar function to print the weather from wttr.in
# Joe Standring <git@joestandring.com>
# GNU GPLv3

# Dependencies: curl

dwm_weather() {

		DATA=$(curl -s 'wttr.in/?format=%c%C+%t\n')
		echo "$DATA"
}

dwm_weather
