#!/bin/sh

# Change BAT1 to whatever your battery is identified as. Typically BAT0 or BAT1
BAT="BAT1"
CHARGE=$(cat /sys/class/power_supply/$BAT/capacity)
STATUS=$(cat /sys/class/power_supply/$BAT/status)

# Do not print anything if charged and not discharging
if [ "$CHARGE" -ge 98 ] && [ "$STATUS" != "Discharging" ]; then
	exit
fi

# Determine icon based on charge percentage
if [ "$CHARGE" -ge 98 ]; then
	ICON=""
elif [ "$CHARGE" -le 20 ]; then
	ICON=" $CHARGE"
elif [ "$CHARGE" -le 40 ]; then
	ICON=" $CHARGE"
elif [ "$CHARGE" -le 60 ]; then
	ICON=""
elif [ "$CHARGE" -le 97 ]; then
	ICON=""
else
	ICON="?"
fi

# Display status with appropriate icon
if [ "$STATUS" = "Charging" ]; then
	printf "%s +\n" "$ICON"
else
	printf "%s\n" "$ICON"

	if [ "$CHARGE" -le 30 ]; then
		notify-send -u critical "Battery ${CHARGE}%"
	fi
fi
