#!/bin/sh

# Handle click actions
case "$BLOCK_BUTTON" in
	1) st -e tmux new-session -A -s update 'yay -Syyu --askremovemake --noconfirm' ;;
	3) notify-send "Available Updates" "$(checkupdates | sed 's/\x1b\[[0-9;]*m//g' | awk '{print $1}' | head -n 20)" ;;
esac

cupd=$(checkupdates | wc -l)
if [ "$cupd" -gt 100 ]; then
	printf " %s\n" "$cupd"
else
	printf "\n"
fi

# Skip downloading updates on metered connections or on "Lopes" Wi-Fi
network=$(iwctl station wlan0 show | grep -Po 'Connected network \K.*' | awk '{$1=$1;print}')
metered=$(networkctl status | grep -c 'metered')

if [ "$network" != "Lopes" ] && [ "$metered" -eq 0 ]; then
	checkupdates -d > /dev/null 2>&1
fi
exit 0
