#!/bin/sh

# A dwm_bar function to display information regarding CPU utilization
# Based on dwm_resources by Joe Standring <git@joestandring.com>
# GNU GPLv3

dwm_cpu () {
	# Gather CPU usage
	CPU_NUM=$(top -bn1 | awk '/Cpu/ {print int($2)}')

	# Only display if CPU utilization is 20% or higher
	if [ "$CPU_NUM" -ge 20 ]; then
		printf " %s%%\n" "$CPU_NUM"
	fi
}

dwm_cpu
